export const MESSAGE_TYPES = {
  COLLECT_IMAGES: "COLLECT_IMAGES",
  SHOW_GALLERY: "SHOW_GALLERY",
  DOWNLOAD_IMAGES: "DOWNLOAD_IMAGES",
  DOWNLOAD_PROGRESS_UPDATE: "DOWNLOAD_PROGRESS_UPDATE",
  MESSAGE_PORT: "MESSAGE_PORT",
};

export const OPTIONS_LIST = {
  COLUMNS: "COLUMNS",
  MIN_WIDTH: "MIN_WIDTH",
  MIN_HEIGHT: "MIN_HEIGHT",
  GALLERY_VIEW: "GALLERY_VIEW",
  DEFAULT_EXTENSION: "DEFAULT_EXTENSION",
};
